apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-kong
  namespace: kong
spec:
  template:
    spec:
      containers:
      - name: proxy
        env:
        - name: KONG_PLUGINS
          value: request-uri-pass-auth,myheader,forward-auth-request
        - name: KONG_LUA_PACKAGE_PATH
          value: "/opt/?.lua;;"
        volumeMounts:
        - name: kong-plugin-request-uri-pass-auth
          mountPath: /opt/kong/plugins/request-uri-pass-auth
        - name: kong-plugin-myheader
          mountPath: /opt/kong/plugins/myheader
        - name: kong-forward-auth-request
          mountPath: /opt/kong/plugins/forward-auth-request
      volumes:
      - name: plugin-request-uri-pass-auth
        configMap:
          name: plugin-request-uri-pass-auth
      - name: my-custom-plugin
        configMap:
          name: my-custom-plugin
      - name: forward-auth-request
        configMap:
          name: forward-auth-request
